---
- name: Get current status of the custom resource
  kubernetes.core.k8s_info:
    api_version: config.onprem.edenlab.io/v1alpha1
    kind: K3SRemoteMachine
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: current_cr_status

- name: Extract current phase
  set_fact:
    current_phase: "{{ current_cr_status.resources[0].status.phase | default('') }}"

- name: test current phase
  debug:
    msg: "{{ current_phase }}"

- name: Set phase '{{ new_phase }}' if it differs from the current one
  operator_sdk.util.k8s_status:
    api_version: config.onprem.edenlab.io/v1alpha1
    kind: K3SRemoteMachine
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      phase: "{{ new_phase }}"
      message: "{{ new_message | default(omit) }}"
  when: >
    current_phase != new_phase and
    expected_previous_phase is defined and current_phase in expected_previous_phase
