---
collections:
  - name: operator_sdk.util
    version: "0.5.0"
  - name: kubernetes.core
    version: "3.2.0"
  - name: cloud.common
    version: "3.0.0"
  - name: ansible.posix
    version: "2.0.0"
  - name: community.docker
    version: "3.12.1"
  - name: community.general
    version: "10.7.0"
