# This rule is not used by the project on-premise-configurator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to config.onprem.edenlab.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: on-premise-configurator
    app.kubernetes.io/managed-by: kustomize
  name: k3scluster-viewer-role
rules:
- apiGroups:
  - config.onprem.edenlab.io
  resources:
  - k3sclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.onprem.edenlab.io
  resources:
  - k3sclusters/status
  verbs:
  - get
