# This rule is not used by the project on-premise-configurator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the config.onprem.edenlab.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: on-premise-configurator
    app.kubernetes.io/managed-by: kustomize
  name: k3scontrolplane-editor-role
rules:
- apiGroups:
  - config.onprem.edenlab.io
  resources:
  - k3scontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.onprem.edenlab.io
  resources:
  - k3scontrolplanes/status
  verbs:
  - get
