# This rule is not used by the project on-premise-configurator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over config.onprem.edenlab.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: on-premise-configurator
    app.kubernetes.io/managed-by: kustomize
  name: k3scontrolplane-admin-role
rules:
- apiGroups:
  - config.onprem.edenlab.io
  resources:
  - k3scontrolplanes
  verbs:
  - '*'
- apiGroups:
  - config.onprem.edenlab.io
  resources:
  - k3scontrolplanes/status
  verbs:
  - get
