---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for config.onprem.edenlab.io/v1alpha1, Kind: K3SRemoteMachine
  ##
  - apiGroups:
      - config.onprem.edenlab.io
    resources:
      - k3sremotemachines
      - k3sremotemachines/status
      - k3sremotemachines/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for config.onprem.edenlab.io/v1alpha1, Kind: K3SCluster
  ##
  - apiGroups:
      - config.onprem.edenlab.io
    resources:
      - k3sclusters
      - k3sclusters/status
      - k3sclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for config.onprem.edenlab.io/v1alpha1, Kind: K3SControlPlane
  ##
  - apiGroups:
      - config.onprem.edenlab.io
    resources:
      - k3scontrolplanes
      - k3scontrolplanes/status
      - k3scontrolplanes/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
# +kubebuilder:scaffold:rules
