apiVersion: config.onprem.edenlab.io/v1alpha1
kind: RemoteMachine
metadata:
  labels:
    app.kubernetes.io/name: on-premise-configurator
    app.kubernetes.io/managed-by: kustomize
  name: agent-02
spec:
  # SSH
  sshUser: ec2-user
  sshUserDisablePassword: true
  # Prepare OS additional disk
#  additionalDiskDevice: "/dev/nvme1n1"
#  additionalDiskFormatted: true
#  additionalDiskMount: true
#  additionalDiskFSType: "ext4"
#  additionalDiskMountPath: "/data/k3s"
  # Prepare OS
  address: 51.21.94.49
  hostname: agent-02
  configureFirewall: true
  disableSelinux: true
  disableSwap: true
  updateSystemPackages: true
  # K3s
  k3sVersion: "v1.31.8+k3s1"
  k3sPrefixSecretRef: "k3s-cluster"
  k3sInitServer: false
  k3sRole: agent
  k3sConfigFile: |
    data-dir: /var/lib/rancher/k3s        
    node-name: agent-02
    server: https://172.31.1.61:6443
    # To select a particular subset of nodes to host pods for a LoadBalancer, add the enablelb label to the desired nodes, 
    # and set matching lbpool label values on the Nodes and Services
    node-label:
      - svccontroller.k3s.cattle.io/lbpool=pool1
      - svccontroller.k3s.cattle.io/enablelb=true
