apiVersion: config.onprem.edenlab.io/v1alpha1
kind: K3SRemoteMachine
metadata:
  labels:
    app.kubernetes.io/name: on-premise-configurator
    app.kubernetes.io/managed-by: kustomize
  name: k3sremotemachine-sample
spec:
  # TODO(user): Add fields here
