apiVersion: config.onprem.edenlab.io/v1alpha1
kind: K3SRemoteMachine
metadata:
  labels:
    app.kubernetes.io/name: on-premise-configurator
    app.kubernetes.io/managed-by: kustomize
  name: server-init
spec:
  # SSH
  sshUser: ec2-user
  sshUserDisablePassword: true
  # Prepare OS additional disk
  additionalDiskDevice: "/dev/nvme1n1"
  additionalDiskFormatted: true
  additionalDiskMount: true
  additionalDiskFSType: "ext4"
  additionalDiskMountPath: "/data/k3s"
  # Prepare OS
  address: 13.61.47.205
  hostname: server-init
  configureFirewall: true
  disableSelinux: true
  disableSwap: true
  updateSystemPackages: true
  # K3s
  k3sVersion: "v1.31.8+k3s1"
  k3sPrefixSecretRef: "k3s-cluster"
  k3sInitServer: true
  k3sRole: server # server|agent
  # CIDR range for intra-cluster Pod networking (Cluster CIDR).
  # This range must be allowed in firewalld to enable Pod-to-Pod communication across nodes.
  # k3sAllowedClusterCIDR: 10.42.0.0/16
  # CIDR range used for ClusterIP services (Service CIDR).
  # This range must be allowed in firewalld to enable access to Kubernetes services across nodes.
  # k3sAllowedServiceCIDR: 10.43.0.0/16
  k3sConfigFile: |
    data-dir: /var/lib/rancher/k3s        
    node-name: server-init
    tls-san:
      - 13.61.47.205
      - 51.21.56.17
      - 56.228.40.74
    write-kubeconfig-mode: "0644"
    cluster-init: true


#    default-local-storage-path: ""
