name: Core Gitflow CI Action workflow

on:
  push:
    # For Gitflow the following patterns are suggested:
    # - master
    # - develop
    # - feature/*
    # - release/*
    # - hotfix/*
    #
    # For an action with image_build_push=false the following patterns are suggested:
    # - master
    branches:
      - master

env:
  # AWS region of the AWS account storing images in AWS ECR.
  CORE_AWS_REGION: eu-north-1

jobs:
  gitflow-ci:
    name: Checkout main repository, run Gitflow CI action
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Generate infrastructure components manifest
        run: |
          # constants for selecting branches
          readonly GITHUB_ORG="${GITHUB_REPOSITORY_OWNER}"
          readonly GITHUB_REPO_NAME="${GITHUB_REPOSITORY#${GITHUB_ORG}/}"
                    
          echo "Git commit message:"
          GIT_COMMIT_MSG="$(git log -1 --pretty=format:"%s")"
          echo "${GIT_COMMIT_MSG}"
        
          if [[ ! "${GIT_COMMIT_MSG}" =~ ^Merge\ pull\ request\ #[0-9]+\ from\ ${GITHUB_ORG}/(hotfix|release)/(v[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            >&2 echo "Pushes to master should be done via merges of PR requests from hotfix/vN.N.N or release/vN.N.N branches only."
            >&2 echo "The expected message format (will be used for parsing a release tag):"
            >&2 echo "Merge pull request #N from ${GITHUB_ORG}/hotfix/vN.N.N or ${GITHUB_ORG}/release/vN.N.N."
            exit 1
          fi
        
          VERSION="${BASH_REMATCH[2]}"
          IMG="public.ecr.aws/${GITHUB_ORG}/core.${GITHUB_REPO_NAME}:${VERSION}" make generate

      - name: Checkout Gitflow CI action repository
        uses: actions/checkout@v4
        with:
          repository: edenlabllc/gitflow.ci.action
          ref: v1
          token: ${{ secrets.GH_TOKEN_REPO_FULL_ACCESS }}
          path: .github/actions/gitflow.ci.action

      - name: Run Gitflow CI action
        uses: ./.github/actions/gitflow.ci.action
        with:
          core_aws_region: ${{ env.CORE_AWS_REGION }}
          core_aws_access_key_id: ${{ secrets.CORE_AWS_ACCESS_KEY_ID }}
          core_aws_secret_access_key: ${{ secrets.CORE_AWS_SECRET_ACCESS_KEY }}
          github_token_repo_full_access: ${{ secrets.GH_TOKEN_REPO_FULL_ACCESS }}
          ecr_public_repository: true
          ecr_repository_name_prefix: core.
          image_delete: false
          image_scan: false
          release_artifacts: |
            dist/infrastructure-components.yaml
