name: Core Gitflow CI Action workflow

on:
  push:
    # For Gitflow the following patterns are suggested:
    # - master
    # - develop
    # - feature/*
    # - release/*
    # - hotfix/*
    #
    # For an action with image_build_push=false the following patterns are suggested:
    # - master
    branches:
      - master

env:
  # AWS region of the AWS account storing images in AWS ECR.
  CORE_AWS_REGION: eu-north-1

jobs:
  gitflow-ci:
    name: Checkout main repository, run Gitflow CI action
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Run Gitflow CI action
        uses: edenlabllc/gitflow.ci.action@v1
        with:
          core_aws_region: ${{ env.CORE_AWS_REGION }}
          core_aws_access_key_id: ${{ secrets.CORE_AWS_ACCESS_KEY_ID }}
          core_aws_secret_access_key: ${{ secrets.CORE_AWS_SECRET_ACCESS_KEY }}
          github_token_repo_full_access: ${{ secrets.GH_TOKEN_REPO_FULL_ACCESS }}
          ecr_public_repository: true
          ecr_repository_name_prefix: core.
          image_delete: false
          image_scan: false
